// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtEoHrnGOsd2EmCMSHUBuolFoIgr56Uao',
    appId: '1:629696079518:web:61139a8606db10a182fd8f',
    messagingSenderId: '629696079518',
    projectId: 'fashion-store-app-51b15',
    authDomain: 'fashion-store-app-51b15.firebaseapp.com',
    storageBucket: 'fashion-store-app-51b15.firebasestorage.app',
    measurementId: 'G-KCB22V5DNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXnDpK_ic3IhMKpWGb7XYjs0kulR2wMJk',
    appId: '1:629696079518:android:26f9200314de3e9682fd8f',
    messagingSenderId: '629696079518',
    projectId: 'fashion-store-app-51b15',
    storageBucket: 'fashion-store-app-51b15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxt7C0ayTUto1vjlOuOzd9G_OabvJf9zY',
    appId: '1:629696079518:ios:d91b42fc8be3d74a82fd8f',
    messagingSenderId: '629696079518',
    projectId: 'fashion-store-app-51b15',
    storageBucket: 'fashion-store-app-51b15.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxt7C0ayTUto1vjlOuOzd9G_OabvJf9zY',
    appId: '1:629696079518:ios:d91b42fc8be3d74a82fd8f',
    messagingSenderId: '629696079518',
    projectId: 'fashion-store-app-51b15',
    storageBucket: 'fashion-store-app-51b15.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtEoHrnGOsd2EmCMSHUBuolFoIgr56Uao',
    appId: '1:629696079518:web:952663ef0567a7e582fd8f',
    messagingSenderId: '629696079518',
    projectId: 'fashion-store-app-51b15',
    authDomain: 'fashion-store-app-51b15.firebaseapp.com',
    storageBucket: 'fashion-store-app-51b15.firebasestorage.app',
    measurementId: 'G-9BM4KCSJFT',
  );
}
